

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.8.4-jdk-11
  script:
    - echo "cleaning in progress"
    - mvn clean
    - echo "Compiling the java source code in progress"
    - mvn compiler:compile
    - mvn compiler:testCompile
    - echo "Building the app in progress"
    - mvn package
    - echo "installing the project file"
    - mvn install 
  artifacts:
      paths:
          - target/*.jar   

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: maven:3.8.4-jdk-11
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - mvn test
    - sleep 60
    - echo "Code coverage is 90%"
  artifacts:
    paths:
        - target/*.jar

